import { useState } from 'react'
import './App.css'

const projects = [
  { n: '01', title: 'AGentic', subtitle: 'Intelligent Study Planner', desc: 'A thoughtful AI study companion that turns learning goals into clear, adaptive plans and keeps progress moving.', tags: ['Python', 'AI', 'Automation'], art: 'agentic', icon: '✳' },
  { n: '02', title: 'Predictive Health System', subtitle: 'Health insights, made clearer', desc: 'A machine learning concept for exploring health data and surfacing useful predictive insights through a simple interface.', tags: ['Python', 'Machine Learning', 'Streamlit'], art: 'health', icon: '⌁' },
  { n: '03', title: 'Smart Mobility Analysis', subtitle: 'Understanding how we move', desc: 'Data analysis and ML come together to explore mobility patterns and imagine more informed urban journeys.', tags: ['Python', 'Data Analysis', 'ML'], art: 'mobility', icon: '↗' },
  { n: '04', title: 'Full Stack Web Projects', subtitle: 'Ideas built for the browser', desc: 'A growing collection of responsive web experiences, bringing polished front ends and practical back ends together.', tags: ['React', 'Node.js', 'JavaScript'], art: 'web', icon: '⌘' },
]
const skills = ['Python', 'Java', 'HTML', 'CSS', 'JavaScript', 'React', 'Node.js', 'SQL', 'MongoDB', 'Git', 'GitHub', 'Data Analysis', 'AI Tools']

function Arrow({ diagonal = false }) { return <span aria-hidden="true" className="arrow">{diagonal ? '↗' : '→'}</span> }

function App() {
  const [theme, setTheme] = useState(() => localStorage.getItem('portfolio-theme') || 'dark')
  const [menuOpen, setMenuOpen] = useState(false)
  const [sent, setSent] = useState(false)
  const toggleTheme = () => setTheme((current) => { const next = current === 'dark' ? 'light' : 'dark'; localStorage.setItem('portfolio-theme', next); return next })
  const closeMenu = () => setMenuOpen(false)

  return <div className={`site ${theme}`}>
    <header className="topbar"><a className="wordmark" href="#home" onClick={closeMenu}><span className="brand-mark">S</span> Saurabh Sen</a>
      <button className="menu-toggle" aria-label={menuOpen ? 'Close navigation' : 'Open navigation'} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}><span/><span/></button>
      <nav className={menuOpen ? 'nav-links open' : 'nav-links'} aria-label="Main navigation"><a href="#resume" onClick={closeMenu}>Resume</a><a href="#about" onClick={closeMenu}>About</a><a href="#projects" onClick={closeMenu}>Projects</a><a href="#contact" onClick={closeMenu}>Contact</a><button className="theme-toggle" onClick={toggleTheme} aria-label={`Switch to ${theme === 'dark' ? 'light' : 'dark'} mode`}>{theme === 'dark' ? '☼' : '☾'}</button></nav>
    </header>
    <main>
      <section className="hero-section" id="home" aria-labelledby="hero-title">
        <div className="hero-grid">
          <article className="card hero-intro"><div className="eyebrow"><span className="status-dot"/> AVAILABLE FOR OPPORTUNITIES</div><p className="hero-kicker">Hello, I’m <span>Saurabh Sen</span></p><h1 id="hero-title">Building digital experiences with <em>code, data &amp; AI.</em></h1><p className="hero-copy">I’m a BCA student exploring the space where intelligent technology meets thoughtful design. I love turning curious questions into useful digital experiences.</p><div className="hero-actions"><a className="button button-gold" href="#resume" id="resume">View Resume <Arrow diagonal /></a><a className="button button-quiet" href="#contact">Let’s talk <Arrow /></a></div><div className="hero-meta"><span>BASED IN BENGALURU, INDIA</span><span className="meta-line"/><span>OPEN TO WHAT’S NEXT</span></div></article>
          <article className="card profile-card"><div className="profile-top"><span className="eyebrow">A LITTLE ABOUT ME</span><span className="card-index">01 — 04</span></div><div className="portrait photo-present"><img className="portrait-image" src={`${import.meta.env.BASE_URL}saurabh-sen.jpeg`} alt="Saurabh Sen"/><div className="portrait-caption">CURIOUS BY NATURE<br/>BUILDER BY CHOICE</div></div><div className="profile-bottom"><div><h2>Saurabh Sen</h2><p>BCA (AI &amp; ML) Student</p></div><span className="university-mark">AU</span></div></article>
          <article className="card focus-card"><span className="eyebrow">CURRENTLY EXPLORING</span><div className="focus-icon">⌘</div><h2>Learning by<br/>building.</h2><p>Turning class concepts into practical projects and new questions into working prototypes.</p><a href="#projects" className="text-link">See what I’m making <Arrow diagonal /></a></article>
          <article className="card degree-card"><span className="eyebrow">THE FOUNDATION</span><div className="degree-number">BCA</div><div className="degree-line"/><div className="degree-details"><div><strong>Artificial Intelligence<br/>&amp; Machine Learning</strong><span>UNDERGRADUATE PROGRAM</span></div><div><strong>Alliance University</strong><span>BENGALURU, INDIA</span></div></div><div className="degree-year">2023 <span>—</span> PRESENT</div></article>
          <article className="card note-card"><span className="quote-mark">“</span><p>Good technology should feel <em>useful, human,</em> and a little bit delightful.</p><span className="note-signature">— MY NORTH STAR</span><div className="note-spark">✳</div></article>
        </div>
      </section>

      <section className="content-section" id="about"><div className="section-heading"><div><span className="eyebrow">A BIT ABOUT ME</span><h2>Curiosity is my<br/><em>favorite tool.</em></h2></div><p>I’m drawn to ideas that make complex things easier to understand—and technology gives me so many ways to explore them.</p></div>
        <div className="about-grid"><article className="card about-card"><div className="about-spark">✳</div><span className="eyebrow">MY APPROACH</span><h3>Learn deeply.<br/>Build with purpose.</h3><p>My interests sit at the intersection of intelligent systems and the products people use every day. From understanding patterns in data to building responsive web experiences, I enjoy taking an idea from “what if?” to “what’s next?”</p><div className="about-footer"><span>ALWAYS IN BETA</span><span>✦ &nbsp; OPEN MINDS, OPEN SOURCE</span></div></article>
        <article className="card interests-card"><span className="eyebrow">WHAT I’M INTO</span><div className="interest-list">{[['01','Artificial Intelligence'],['02','Machine Learning'],['03','Software Development'],['04','Data Analysis'],['05','Web Development']].map(([n, label])=><div className="interest-row" key={n}><span>{n}</span><strong>{label}</strong><Arrow diagonal /></div>)}</div></article>
        <article className="card skills-card"><div className="skills-heading"><span className="eyebrow">TOOLS I WORK WITH</span><span className="skill-count">13 SKILLS</span></div><div className="skill-cloud">{skills.map((skill, i)=><span className={`skill-chip ${i < 3 ? 'highlight' : ''}`} key={skill}>{skill}</span>)}</div><div className="skills-foot">A TOOLBOX THAT’S ALWAYS GROWING <span>↗</span></div></article></div>
      </section>

      <section className="content-section projects-section" id="projects"><div className="section-heading projects-heading"><div><span className="eyebrow">SELECTED WORK · 2024—26</span><h2>Ideas, meet<br/><em>execution.</em></h2></div><p>A few directions I’ve been exploring. Each project is a chance to learn something new and make something useful along the way.</p></div>
        <div className="project-grid">{projects.map((project) => <article className="card project-card" key={project.n}><div className={`project-art ${project.art}`}><span className="project-number">PROJECT / {project.n}</span><div className="art-visual"><span className="art-icon">{project.icon}</span><div className="art-rings"/><div className="art-orb"/></div><span className="art-label">{project.subtitle}</span></div><div className="project-body"><div className="project-title-row"><div><span className="project-type">FEATURED PROJECT</span><h3>{project.title}</h3></div><span className="project-arrow"><Arrow diagonal /></span></div><p>{project.desc}</p><div className="project-tags">{project.tags.map(tag=><span key={tag}>{tag}</span>)}</div><div className="project-links"><a href="https://github.com/saurabhsen848" target="_blank" rel="noreferrer">GitHub <Arrow diagonal /></a><a href="#contact">Live demo <Arrow diagonal /></a></div></div></article>)}</div>
      </section>

      <section className="connect-band"><div><span className="eyebrow">AROUND THE WEB</span><h2>Find me <em>out there.</em></h2></div><div className="social-links"><a href="https://github.com/saurabhsen848" target="_blank" rel="noreferrer"><span className="social-symbol">⌘</span><span>GitHub<small>CODE &amp; PROJECTS</small></span><Arrow diagonal /></a><a href="https://www.linkedin.com/in/saurabhsen848/" target="_blank" rel="noreferrer"><span className="social-symbol">in</span><span>LinkedIn<small>LET’S CONNECT</small></span><Arrow diagonal /></a><a href="https://saurabhsen848.github.io/saurabh-portfolio/" target="_blank" rel="noreferrer"><span className="social-symbol">↗</span><span>Portfolio<small>THE OTHER CORNER</small></span><Arrow diagonal /></a></div></section>

      <section className="content-section contact-section" id="contact"><div className="section-heading contact-heading"><div><span className="eyebrow">HAVE A GOOD ONE IN MIND?</span><h2>Let’s make<br/><em>it happen.</em></h2></div><p>Have a project, an opportunity, or just want to talk about technology? Connect with me on LinkedIn or GitHub.</p></div><div className="contact-grid"><article className="card contact-info"><span className="eyebrow">GET IN TOUCH</span><h3>Good things<br/>start with hello.</h3><p className="contact-message">I’m easiest to reach through my social profiles. I’d love to hear what you’re working on.</p><div className="contact-social"><a href="https://www.linkedin.com/in/saurabhsen848/" target="_blank" rel="noreferrer">LinkedIn <Arrow diagonal /></a><a href="https://github.com/saurabhsen848" target="_blank" rel="noreferrer">GitHub <Arrow diagonal /></a></div><div className="contact-decoration">✳</div></article><form className="card contact-form" onSubmit={(event)=>{event.preventDefault();setSent(true)}}><div className="form-heading"><span className="eyebrow">SEND A NOTE</span><span className="form-aside">MESSAGE PREVIEW</span></div><label htmlFor="name">Your name</label><input id="name" name="name" placeholder="Jane Smith" required/><label htmlFor="email">Email address</label><input id="email" name="email" type="email" placeholder="jane@example.com" required/><label htmlFor="message">What’s on your mind?</label><textarea id="message" name="message" rows="3" placeholder="Tell me a little about it..." required/><button className="button button-gold submit-button" type="submit">{sent ? 'Message noted' : 'Send message'} <Arrow diagonal /></button><p className="form-note" aria-live="polite">{sent ? 'This demo form does not deliver messages yet. Please reach out via LinkedIn or GitHub.' : 'Form preview only. For a reply, contact me on LinkedIn or GitHub.'}</p></form></div></section>
    </main>
    <footer className="footer"><a className="wordmark" href="#home"><span className="brand-mark">S</span> Saurabh Sen</a><span>DESIGNED WITH CURIOSITY · BUILT WITH CARE</span><a className="back-top" href="#home">BACK TO TOP ↑</a><span className="copyright">© 2026 SAURABH SEN</span></footer>
  </div>
}

export default App
